#!/bin/sh
#
# Copyright © 2015-2024 the original authors.
# SPDX-License-Identifier: Apache-2.0
#
# Gradle start up script for POSIX generated by Gradle.
# Колин: Этот скрипт запускает Gradle Wrapper на Linux/Mac

# Добавляем цвета для красивого вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo "${GREEN}║         Root24h Gradle Wrapper v8.4                     ║${NC}"
echo "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"

# Определяем директорию, где находится скрипт
APP_HOME=$(cd "$(dirname "$0")" && pwd)

# Добавляем APP_HOME в PATH
export PATH=$APP_HOME:$PATH

# Java опции по умолчанию
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Использовать CDS (Class Data Sharing) для ускорения
USE_CDS=true

# Функция для определения Java
find_java() {
    if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
        JAVA_CMD="$JAVA_HOME/bin/java"
    elif type java >/dev/null 2>&1; then
        JAVA_CMD=java
    else
        echo "${RED}❌ Java не найдена! Установите JDK 17 или новее.${NC}"
        exit 1
    fi
    
    # Проверяем версию Java
    JAVA_VERSION=$("$JAVA_CMD" -version 2>&1 | head -1 | cut -d'"' -f2 | sed 's/^1\.//' | cut -d'.' -f1)
    if [ "$JAVA_VERSION" -lt 17 ]; then
        echo "${YELLOW}⚠️  Java версии $JAVA_VERSION устарела. Рекомендуется JDK 17+${NC}"
    else
        echo "${GREEN}✅ Java версии $JAVA_VERSION найдена${NC}"
    fi
}

# Функция для проверки интернета
check_internet() {
    if ping -c 1 google.com >/dev/null 2>&1; then
        echo "${GREEN}✅ Интернет доступен${NC}"
        return 0
    else
        echo "${YELLOW}⚠️  Нет интернета. Будет использован кэш Gradle${NC}"
        return 1
    fi
}

# Основная функция
main() {
    echo "${GREEN}🔧 Инициализация Gradle Wrapper...${NC}"
    
    # Находим Java
    find_java
    
    # Проверяем интернет
    check_internet
    
    # Формируем команду
    CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
    
    # Добавляем опции для ускорения
    JVM_OPTS=""
    if [ "$USE_CDS" = true ]; then
        JVM_OPTS="$JVM_OPTS -XX:+UseAppCDS"
    fi
    
    # Запускаем Gradle
    echo "${GREEN}🚀 Запуск Gradle...${NC}"
    "$JAVA_CMD" $JVM_OPTS -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
    
    # Проверяем результат
    if [ $? -eq 0 ]; then
        echo "${GREEN}✅ Сборка завершена успешно!${NC}"
    else
        echo "${RED}❌ Ошибка сборки!${NC}"
        exit 1
    fi
}

# Запускаем
main "$@"
